/*
Copyright © 2022 Fontaine Coutino
*/

// GENERATE PASSWORD AND LET USER PICK STRENGTH TYPE (UNSAFE/SAFE/STRONG/SRONGEST)
// GENERTAE PASSWORD BASED ON ATRTIBUTES (LENGTH/TYPE OF CHARS)
// GENERATE PASSWORD SUBSTITUTING CHARACTERS IN WORD TO ASCII VALS

package main

import "github.com/fcoutino/passgen/cmd"

func main() {
	cmd.Execute()
}
